name: photostock
version: "0.0.1-dev.0"
description: photostock
publish_to: none

dependencies:
  auto_route: ^7.8.4
  blurhash: ^1.1.1
  collection: any
  dio: ^5.3.3
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  firebase_core: ^2.19.0
  firebase_crashlytics: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  infinite_scroll_pagination: ^4.0.0
  intl: any
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  union_state: ^0.0.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  elementary_test: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: ^8.0.1
  spider: ^4.2.2
  surf_lint_rules: ^3.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ^3.10.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
